# Generated by Django 5.2.16 on 2026-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('category', models.CharField(max_length=100)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'author'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_copies__gte', 0)), name='book_total_copies_non_negative'), models.CheckConstraint(condition=models.Q(('available_copies__gte', 0)), name='book_available_copies_non_negative'), models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='book_available_not_more_than_total')],
            },
        ),
    ]
