# Generated by Django 5.2.16 on 2026-08-05 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('loans', '0002_loan_unique_active_loan_per_user_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_active_loan_per_user_book',
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Borrowed')), fields=('book', 'member'), name='unique_active_loan_per_user_book'),
        ),
    ]
